In [1]:
import numpy as np

In [ ]:
#NUMPY----->we will working with multi dimensional arrys!!

In [3]:
array_one=np.array([1,2,3,4])

In [5]:
array_one

array([1, 2, 3, 4])

In [7]:
type(array_one)

numpy.ndarray

In [8]:
numbers=[1,2,3,4,5]

In [9]:
array_two=np.array(numbers)

In [10]:
array_two

array([1, 2, 3, 4, 5])

In [11]:
type(array_two)

numpy.ndarray

In [ ]:
#array of zeros:--------------->

#it is used to display a null matrix

In [12]:
array_of_zero=np.zeros((3,4))  # 3---for rows
                               # 4 for columns

In [14]:
array_of_zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
type(array_of_zero)

numpy.ndarray

In [ ]:
#numpy uses float data type default------>see the above arraarray_of_zero matrix

In [17]:
array_of_ones=np.ones((4,5))

In [18]:
array_of_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
#identiry matrix---------->

In [20]:
array_eye=np.eye(3)

In [21]:
array_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#range(start _value,stop_value,step_count)

In [26]:
#arange()

In [28]:
#req:- I ewant to print even numbers from 1 to 50
****

In [29]:
array_of_even=np.arange(2,50,2)

In [30]:
array_of_even

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48])

In [ ]:
#stop value is always exclusive 

In [ ]:
#creating an arry of two dimensionsl

In [31]:
array_2d=np.array([(2,3,5),(5,4,6)])

In [32]:
array_2d

array([[2, 3, 5],
       [5, 4, 6]])

In [ ]:
#how to validate the dimensions

In [33]:
array_2d.shape

(2, 3)

In [34]:
#2--rows
#3--colmns